# Generated by Django 4.2.7 on 2023-11-13 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_location_profile_favorite_court_and_more'),
        ('courts', '0002_remove_court_court_name_remove_court_location_and_more'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='court',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='courts.court'),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='hosted_events', to='users.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='event',
            name='player_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='players',
            field=models.ManyToManyField(related_name='events', to='users.profile'),
        ),
        migrations.AddField(
            model_name='event',
            name='public_or_private',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='teams_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
