# Generated by Django 4.2.7 on 2023-11-13 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='court',
            name='court_name',
        ),
        migrations.RemoveField(
            model_name='court',
            name='location',
        ),
        migrations.AddField(
            model_name='court',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='court',
            name='email',
            field=models.EmailField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='court',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='court',
            name='open_hours',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='court',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_courts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='court',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='court',
            name='pictures',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='court',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
